server:
  port: 8081

spring:
  profiles:
    active: dev #默认为开发环境

# mybatis配置
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
  #开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-manager-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单 (不需要进行身份认证的路径)  (逗号后面指定允许的方法)
      - /swagger_login
      - /swagger/login/check
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /api/user/**/login
      - /api/user/**/register
      - /api/home/**/pageContentInfo
      - /api/home/**/pageListInfo
      - /api/home/**/getCategoryList
